### ISSUE TITLE
Load Error 1.15.2 [BUG]

### ISSUE THREAD

**Issue by teagan75** [Stereowalker/C.O.M.B.A.T#107]
**Describe the bug**
My game was fine till I decided to add your mod. Now it fails to load. Tried downgrading a few versions still with issues.

**Logs**
https://pastebin.com/Gxxu8u6N

**Expected behavior**
I expected the mod to load properly.

**Screenshots**
![error](https://user-images.githubusercontent.com/12485764/129388887-e9b6d585-66f3-4b38-9399-dbb4a092f839.png)

**Minecraft Environment:**
 - Forge Version: 31.2.55
 - UnionLib Version: 1.15.2-3.2.6
 - C.O.M.B.A.T Version: 1.15.2-4.9.4

**Comment by Stereowalker** [comment]
This is a pretty dated version of the mod. A lot has changed and this version of the mod is no longer being maintained so I'm closing this issue.

**Comment by Stereowalker** [comment]
You should update to 1.16.5, the grass is greener there

**Comment by Stereowalker** [comment]
There are lots more features and even more in the works

**Comment by teagan75** [comment]
As I am using Mine and Slash and they haven’t updated yet that is impossible. I will just not use your mod

**Comment by Stereowalker** [comment]
Good luck in your endeavors. Give this mod a whirl when you eventually update to 1.16.5, you'll definitely enjoy the ride

**Comment by teagan75** [comment]
I don't know. You have left a release unplayable which leaves a bad taste
in my mouth since I am a modpack dev. I cannot load your mod alone in the
version you say is a stable release in 1.15.2

**Comment by Stereowalker** [comment]
I was quite the caterpillar then and made really immature decisions. I backported a few of my mods to 1.15, but I can't do that for this one as the dimension and world gen code is a lot different compared to 1.16, and even if I wanted to port it back from the old code, that is also lost to the wind. I didn't make backups at the time so I'm really at a loss when it comes to helping you here
