### ISSUE TITLE
[BUG] Crash Upon New World

### ISSUE THREAD

**Issue by Lonemind** [Stereowalker/C.O.M.B.A.T#110]
**Describe the bug**
[Crashes before startup.]

**Logs**
[Crash Report]
https://pastebin.com/YubREztN

[Console Log Before Crash]
https://pastebin.com/Ly1H3Psh

**To Reproduce**
[1.) Install Mod
2.) Startup Minecraft
3.) Prof... er... Cry in sorrow over crash]

**Expected behavior**
[Start up Minecraft and try out a really cool looking magic mod that got me all excited.]

**Screenshots**
[Cute Cat]
https://imgur.com/gallery/4clqUdj

**Minecraft Environment:**
 - Forge Version: 40.1.52
 - UnionLib Version: 7.1.1
 - C.O.M.B.A.T Version: 9.0.1

**Additional context**
[Add any other context about the problem here.]

**Comment by Stereowalker** [comment]
Do you have any other mods installed? If you do, one of them might be privating the field that I'm trying to access

**Comment by Lonemind** [comment]
I had multiple mods installed and the funny thing was that Minecraft loaded fine until I tried making a new world. Then it crashed. So I removed all my mods and only had COMBAT and Union. That's when it started crashing while loading.

**Comment by Lonemind** [comment]
It appears that the problem I was having has vanished with the newest versions. Thank you for looking into it, Stereowalker.
