### ISSUE TITLE
crashing server on player join(1.15.2-forge-1.15.2-31.1.14)

### ISSUE THREAD

**Issue by SDUBZ** [Stereowalker/C.O.M.B.A.T#24]
forge: forge-1.15.2-31.1.14
combat:
C.O.M.B.A.T.-1.15.2-3.0.7.jar
logs:
latest:
https://gist.github.com/SDUBZ/547030d5cfbd77f7f945285d1e8061f3
debug:
https://gist.github.com/SDUBZ/938e07ae6a23520ddabbcabb0b13e08b

**Comment by Stereowalker** [comment]
I hope v3.0.8 solves this issue for you

**Comment by SDUBZ** [comment]
it is fixed thank you and newer versions work too i will close this now
