### ISSUE TITLE
temperature

### ISSUE THREAD

**Issue by iobiarg** [Stereowalker/C.O.M.B.A.T#25]
Hi there, i've been using your mod for a couple of weeks i think, and at least with this last update, even if the thermometer says its 35° in a biome that at least to my knowledge is pretty hi and would make you sweat like a pig, i get hypothermia. Then there is no way of getting rid of it. I even steeped into lava, over furnace in a fire pit, inside a village house... I'm disabling the temperature config because i can't get rid of it... i may be stupid but since i don't have any warmer biome close, dunno how to fix it

**Comment by Stereowalker** [comment]
Thanks for informing me

**Comment by Stereowalker** [comment]
Update to 4.0.0.

**Comment by Stereowalker** [comment]
and tell me what you think

**Comment by iobiarg** [comment]
ok, i'll reinstall... btw, there should be a way to drink water before getting to glass... i remember there was  a mod in 1.12 i think, that you could actually drink from any river/ocean but there was side effects like nausea or sth but made easier to pass first night when not using other mods... anyhow, thanks for noting my message.

**Comment by Stereowalker** [comment]
Sneak click on water to drink without a bottle

**Comment by Stereowalker** [comment]
*source water block
