### ISSUE TITLE
Temperature in the Nether

### ISSUE THREAD

**Issue by PADORU** [Stereowalker/C.O.M.B.A.T#27]
The temperature system makes me have 75C' in the Nether where I can't drop a water bucket due to ingame rules. Same with Thrist. Are there Items to counteract this?

**Comment by Stereowalker** [comment]
Make a Heat Resistance potion, and also put ice in the nether. Staying near ice will cool you down
Although, with the update, if you avoid lava, magma and fire your temperature won't rise too quickly.
