### ISSUE TITLE
Mobs don't drop their soul gems anymore (happening since 4.0.1)

### ISSUE THREAD

**Issue by m-vlad** [Stereowalker/C.O.M.B.A.T#30]
Hello again, I've noticed that now whenever I kill a mob they drop an Empty Soul Gem. Has the mechanic been modified or is this a bug? It worked correctly in 3.0.6 as in it dropped the mob-specific soul gem.

**Comment by Stereowalker** [comment]
The mechanic has changed. Undead will drop empty soul gems and if you have an empty soul gem when you kill anything that isn't undead, the empty soul gem will become a soul gem

**Comment by m-vlad** [comment]
I see, thank you. When you've got some extra time the wiki could use an update then. Thanks for this great mod :)
