### ISSUE TITLE
error when loading game in  1.5.2

### ISSUE THREAD

**Issue by carlansor** [Stereowalker/C.O.M.B.A.T#32]
Hi, first of all, this is such a nice mod to play with! thank you a lot for it.
The issue is that, in 1.5.2 versions prior to 4.0.3, the game wont start. It says that COMBAT had some error during launching, and leads to curios API file. Here is the log:

https://pastebin.com/SCWLyDnH

**Comment by Stereowalker** [comment]
check 4.0.7 for I have solved it there
