### ISSUE TITLE
random crash why testing with virtual server[1.15.2]

### ISSUE THREAD

**Issue by SDUBZ** [Stereowalker/C.O.M.B.A.T#33]
Forge: 31.1.18
combat: C.O.M.B.A.T-1.15.2-4.0.9
crash:
[crash-2020-03-07_17.45.32-server.txt](https://github.com/Stereowalker/C.O.M.B.A.T/files/4301463/crash-2020-03-07_17.45.32-server.txt)

logs:
[debug.log](https://github.com/Stereowalker/C.O.M.B.A.T/files/4301464/debug.log)
[latest.log](https://github.com/Stereowalker/C.O.M.B.A.T/files/4301466/latest.log)

**Comment by Stereowalker** [comment]
Does 4.1.0 help with your issue?

**Comment by SDUBZ** [comment]
server is launching with newer versions thank you for your work and what you have created
