### ISSUE TITLE
Locate command shows C.O.M.B.A.T.'s structures with minecraft namespace

### ISSUE THREAD

**Issue by TelepathicGrunt** [Stereowalker/C.O.M.B.A.T#34]
I notice when trying out this mod that using the locate command shows COMBAT's structures with minecraft's namespace instead of COMBAT's mod ID
![image](https://user-images.githubusercontent.com/40846040/76156312-bd10b000-60c6-11ea-8872-dd4780e60010.png)

This is a super simple fix if I remember correctly when I had this issue with my mods. In your structure's classes, find the getStructureName method and just add your mod ID + a semicolon to your structure's name. Then MC will recognize that it is a full resource location and won't need to add "minecraft:" to the front of your structure's name in the locate command. :)

```
@Override
	public String getStructureName()
	{
		return ModMain.MODID + ":structure_name";
	}
```

**Comment by Stereowalker** [comment]
Thanks for informing me, I actually had no idea and thought that was the way forge did things
