### ISSUE TITLE
Acrotlest issue

### ISSUE THREAD

**Issue by denbennit** [Stereowalker/C.O.M.B.A.T#36]
It took an hour and a half to actually find the damn thing and when i tried to enter the portal it did absolutely nothing. Any help?

**Comment by Stereowalker** [comment]
You're supposed to stand in the portal for about 10 seconds

**Comment by Stereowalker** [comment]
It doesn't teleport you in an instant

**Comment by denbennit** [comment]
> It doesn't teleport you in an instant

I have stood in the portal for 5 minutes straight and it still did nothing, also, can you clarify on how to upgrade the wands? I have tried everything and nothing works, could you somehow show me a screenshot of how to upgrade?

**Comment by Stereowalker** [comment]
What version are you using

**Comment by denbennit** [comment]
> What version are you using

1.15.2

**Comment by denbennit** [comment]
> What version are you using

Also, can you send screenshots of crafting recipes of the different ways to upgrade the wands?

**Comment by Stereowalker** [comment]
I mean of the mod

**Comment by Stereowalker** [comment]
You'll have to wait a while for the screenshots

**Comment by Stereowalker** [comment]
![2020-03-13_08 04 54](https://user-images.githubusercontent.com/35645830/76666924-46255c80-6589-11ea-9695-05f942c5bc5d.png)
![2020-03-13_08 09 43](https://user-images.githubusercontent.com/35645830/76667000-4e7d9780-6589-11ea-9c40-4e9ad5193f24.png)

**Comment by Stereowalker** [comment]
1st Screenshot: If you're standing in the portal like this and nothing is happening, right after you enter the portal for about 10 seconds send your logs
2nd Screenshot: The format for upgrading your wand is this, for the other ranks follow https://github.com/Stereowalker/C.O.M.B.A.T/wiki/Magical-Items#raising-wand-ranks

**Comment by SDUBZ** [comment]
@Stereowalker i entered this dimension and it kicked me from a testing server 
then gave me bad packet 
![image](https://user-images.githubusercontent.com/14084377/76829221-bfb59700-6876-11ea-8d3e-5b72b13fa9fe.png) 
using : C.O.M.B.A.T-1.15.2-4.2.0
Forge : 31.1.24
server logs:
[debug.log](https://github.com/Stereowalker/C.O.M.B.A.T/files/4341839/debug.log)
[latest.log](https://github.com/Stereowalker/C.O.M.B.A.T/files/4341841/latest.log)

client log:
[latest.log](https://github.com/Stereowalker/C.O.M.B.A.T/files/4341842/latest.log)

This happens after entering the portal

**Comment by Stereowalker** [comment]
Thanks, I'll see what I can do with this

**Comment by Stereowalker** [comment]
Um hey, it's been a while. I've uploaded an update that seems to fix this portal issue that we've been having for a while. Could you check it out and give your feedback?

**Comment by SDUBZ** [comment]
i wish i could tell you because i have other crashes from other mods which are stopping me joining my server lol
