### ISSUE TITLE
Thirst bug

### ISSUE THREAD

**Issue by emanuele246gi** [Stereowalker/C.O.M.B.A.T#37]
When I try to drink from a source of water, I can't fill the thirst bar, only leaving the world and then returning in it will fix the bug

**Comment by DrDarkfire** [comment]
from what my team and I have discovered is that you need to be actually looking at a block with this action

**Comment by emanuele246gi** [comment]
I know that, but sometimes it doesn't work, sometimes even eliminate the drops gained from drinking

**Comment by Stereowalker** [comment]
I see and understand the issue and I've fixed it, but I've removed those features from C.O.M.B.A.T and moved them to a new mod Survive, though that mod hasn't been approved by curse yet

**Comment by Stereowalker** [comment]
But if you still want the feature, and don't want to wait for curse to approve it join my discord and get the file there https://discord.gg/8MXShqa

**Comment by emanuele246gi** [comment]
Thank you! I immediately proceeded
