### ISSUE TITLE
[1.15.2] Dedicated server crash on first load Failed to register automatic subscribers. ModID: combat

### ISSUE THREAD

**Issue by ProsperCraft** [Stereowalker/C.O.M.B.A.T#41]
Stacktrace- https://gist.github.com/ProsperCraft/2081c55ef871ec80ec2f6151b0089f71

Crash report-https://gist.github.com/ProsperCraft/a0a64d1c5d325c9adde962804e21d721

debug log- https://gist.github.com/ProsperCraft/463c08b2aca1ce85824a84ad10f7ea76

C.O.M.B.A.T-1.15.2-4.2.2
forge-1.15.2-31.1.30

**Comment by Stereowalker** [comment]
Please update the mod to 4.3.0 and test again to see if the error occurs again

**Comment by SDUBZ** [comment]
4.3.0 still crashes server side
[debug.log](https://github.com/Stereowalker/C.O.M.B.A.T/files/4426777/debug.log)
[latest.log](https://github.com/Stereowalker/C.O.M.B.A.T/files/4426779/latest.log)
[crash-2020-03-04_16.27.19-server.txt](https://github.com/Stereowalker/C.O.M.B.A.T/files/4426853/crash-2020-03-04_16.27.19-server.txt)

Forge: forge-1.15.2-31.1.35
combat: C.O.M.B.A.T-1.15.2-4.3.0

**Comment by sandalle** [comment]
Same, with forge-1.15.2-31.1.25 for me. Works fine on a client and creating/playing a single-player world, but a dedicated server (Linux) crashes.

crash-report: [crash-2020-04-04_05.10.56-server.txt](https://github.com/Stereowalker/C.O.M.B.A.T/files/4430791/crash-2020-04-04_05.10.56-server.txt)

**Comment by Stereowalker** [comment]
Is this still an issue for anybody?

**Comment by SDUBZ** [comment]
i wish i could tell you because i have other crashes from other mods which are stopping me joining my server lol
