### ISSUE TITLE
Disenchanter: Shift-clicking item crash

### ISSUE THREAD

**Issue by Shorepion** [Stereowalker/C.O.M.B.A.T#44]
Shift-clicking an enchanted book into the Disenchanter causes a crash.

**Comment by Stereowalker** [comment]
Thanks for informing me about the issue, I never would have noticed

**Comment by Shorepion** [comment]
no problem!

**Comment by Shorepion** [comment]
No problem!

**Comment by Shorepion** [comment]
You're welcome!
