### ISSUE TITLE
Crash in game

### ISSUE THREAD

**Issue by emanuele246gi** [Stereowalker/C.O.M.B.A.T#45]
I'm using the latest version of Combat in MC 1.15.2 (latest forge version)

Here there is the link for the crash report
https://pastebin.com/nERMvj6Z

**Comment by Stereowalker** [comment]
Thanks for showing this

**Comment by emanuele246gi** [comment]
No problem man :D

**Comment by Stereowalker** [comment]
Please can you confirm if this issue is still occurring in 4.8.9

**Comment by emanuele246gi** [comment]
Nope man, it doesn't but now I have another problem, I will make another post where you can see it
