### ISSUE TITLE
Crash when loading a world

### ISSUE THREAD

**Issue by emanuele246gi** [Stereowalker/C.O.M.B.A.T#46]
This is really unexpected, I don't have this mod at the moment :/

https://pastebin.com/a0T4VgFU

**Comment by Stereowalker** [comment]
You don't have "Survive" installed right?

**Comment by emanuele246gi** [comment]
Nope I don't have it

**Comment by emanuele246gi** [comment]
Also, I deleted every file about that mod after I removed it, exactly to avoid this kind of problem

**Comment by Stereowalker** [comment]
Check out 4.8.12

**Comment by emanuele246gi** [comment]
Thanks I'll try it later :D

**Comment by emanuele246gi** [comment]
Yeee It worked! Thank you so much man!
