### ISSUE TITLE
xp ring won't give experience

### ISSUE THREAD

**Issue by Jbird127** [Stereowalker/C.O.M.B.A.T#48]
I've gathered quite a bit of experience while wearing the xp ring, but whenever I hold crouch and press right-click it just equips it without giving back any of the experience.

**Comment by Stereowalker** [comment]
for now, equip two rings while you crouch-click on the ring to prevent the ring from being equipped, that way you can collect your experience

**Comment by Stereowalker** [comment]
I've fixed it. You can crouch and right click to collect your experience. But if you right click normally, you equip the ring

**Comment by Jbird127** [comment]
Awesome!  Thanks so much!
