### ISSUE TITLE
Backpack Dupe Bug

### ISSUE THREAD

**Issue by Dunkmania101** [Stereowalker/C.O.M.B.A.T#49]
The backpack seems to have a dupe bug. Specifically, I put an item in it, took the item out, and moved the backpack to a different slot while it was still open and the item was still there. I think it needs to remove the item's nbt at a different time, probably upon removal, if that's possible (I just got started modding  :).

**Comment by Stereowalker** [comment]
Can you give me a step by step on how to recreate this, because I've tried and it doesn't seem to dupe items. Although I'm more familiar with the bug that deletes items when you put Items in the backpack and remove the backpack from your inventory

**Comment by Dunkmania101** [comment]
The issue still seems to exist in the latest version (1.15.2-4.9.4). As for the instructions, I got them backward in the original post. What actually happens is I put something in the backpack, move the backpack to a different slot (or just pick it up and put it back in the same slot), _**then**_ take the item out, close it, and finally open it again and the item is still there. Sorry about that!
