### ISSUE TITLE
crash log from player

### ISSUE THREAD

**Issue by stepsword** [Stereowalker/C.O.M.B.A.T#52]
Hi, 

I'm Mahou Tsukai Dev, someone gave me a crash log that happens when your mod is installed and they use a spell (Mental Displacement) on mine that changes the renderViewEntity.

If this is a simple null pointer check on your end could you do so or if it's something I'm returning that's null, that's supposed to be non-null could you tell me which method?

https://pastebin.com/26Pma4Am <-- Here's the crash log

**Comment by Stereowalker** [comment]
I've added a null check for the player on my end, can you confirm it to be working now?

**Comment by stepsword** [comment]
Unfortunately I get this error on startup: 
https://pastebin.com/n1mDVdf3

**Comment by stepsword** [comment]
Nevermind actually - that crash appears on a pack where I just updated the mod, but if I make a new pack and start it, it works fine. And also the crash seems to be fixed. Thank you!
