### ISSUE TITLE
Compatibility with Mantle

### ISSUE THREAD

**Issue by emanuele246gi** [Stereowalker/C.O.M.B.A.T#58]
Basically, Mantle add the possibility to overlap the hearts in the health bar, instead to make than one above the other, but the problem is that the Mana bar still keeps going up even when the hearts are all at the same height, making the visual very intrusive :/ 
Can you guys fix this?

**Comment by Stereowalker** [comment]
Got it

**Comment by emanuele246gi** [comment]
Thank you :)
Love the mod anyway :D

**Comment by Stereowalker** [comment]
Please confirm if the mod works perfectly fine with mantle

**Comment by emanuele246gi** [comment]
Well I'm sorry that it's too late, but the version is 1.15.2, sorry for saying that too late, my fault 😅

**Comment by Stereowalker** [comment]
Well, I've set it up in 1.16.1 so when you update your game you should see it

**Comment by emanuele246gi** [comment]
Please do it for 1.15.2 too, I can take it anymore, I was expecting to update my modpack to 1.16 soon but somehow I can't yet and for now I have to stay in this version
