### ISSUE TITLE
[Bug]double mana bar

### ISSUE THREAD

**Issue by Eowomir7** [Stereowalker/C.O.M.B.A.T#60]
I've been testing this inside of a custom mod pack I've been working on. **I noticed with your Survive mod installed i get a duplicate mana bar to the right hand side of my screen.** about 30 pixels to the right of the normal mana bar. I'm unsure what is causing this. but after some troubleshooting i have realized **it happens with the Survive energy system turned on**

**Update:** Upon further troubleshooting. **I reproduced the Bug with the energy system off.** this time i reproduced it by leveling up my hp stat, and defense stats. which caused a 2nd health bar above the vanilla one and made the armor bar appear. Though this is an expected behavior, getting a duplicated mana bar to the right side is not.

**What seems to be happening is, whenever the vanilla HUD adds 3 rows below the mana bar. it duplicates the mana bar.**

version C.O.M.B.A.T. 1.16.1-5.2.0
version Survive 1.16.1-2.2.0
version Unionlib 1.16.1-2.2.0
Forge 1.16.1 32.0.98

- steps to reproduce: Set the Survive config option for energy/stamina system to true. open the game. load a world. 2 mana bars

- **Update:** steps to reproduce: Open a world. level up your health attribute till hp>10 hearts, level up your Defense stat. 2 mana bars. 

- **Common occurrence: 3 rows below mana bar on HUD**

**Comment by Stereowalker** [comment]
I'll see how I can fix this issue

**Comment by Stereowalker** [comment]
After 2 months of bug chasing, I believe I've fixed the issue. If you're still observing it then create another issue
