### ISSUE TITLE
Can't destroy blocks properly at high enough levels

### ISSUE THREAD

**Issue by MattyExie** [Stereowalker/C.O.M.B.A.T#63]
11.09 16:52:59 [Server] Server thread/WARN Mismatch in destroy block pos: BlockPos{x=834, y=66, z=152} BlockPos{x=832, y=65, z=152}
11.09 16:52:59 [Server] Server thread/WARN Mismatch in destroy block pos: BlockPos{x=834, y=66, z=152} BlockPos{x=833, y=65, z=152}
11.09 16:52:59 [Server] Server thread/WARN Mismatch in destroy block pos: BlockPos{x=834, y=66, z=152} BlockPos{x=833, y=65, z=151}
11.09 16:53:02 [Server] Server thread/WARN Mismatch in destroy block pos: BlockPos{x=834, y=66, z=152} BlockPos{x=833, y=65, z=154}
11.09 16:53:03 [Server] Server thread/WARN Mismatch in destroy block pos: BlockPos{x=834, y=66, z=152} BlockPos{x=833, y=65, z=152}
11.09 16:53:03 [Server] Server thread/WARN Mismatch in destroy block pos: BlockPos{x=834, y=66, z=152} BlockPos{x=833, y=65, z=153}
11.09 16:53:03 [Server] Server thread/WARN Mismatch in destroy block pos: BlockPos{x=834, y=66, z=152} BlockPos{x=834, y=65, z=153}
11.09 16:53:03 [Server] Server thread/WARN Mismatch in destroy block pos: BlockPos{x=834, y=66, z=152} BlockPos{x=834, y=65, z=154}
11.09 16:53:03 [Server] Server thread/WARN Mismatch in destroy block pos: BlockPos{x=834, y=67, z=152} BlockPos{x=834, y=65, z=154}
11.09 16:53:03 [Server] Server thread/WARN Mismatch in destroy block pos: BlockPos{x=834, y=66, z=152} BlockPos{x=834, y=65, z=154}
11.09 16:53:03 [Server] Server thread/WARN Mismatch in destroy block pos: BlockPos{x=834, y=67, z=152} BlockPos{x=834, y=65, z=154}

**Comment by Stereowalker** [comment]
Did you attempt this with only this mod installed?
