### ISSUE TITLE
[BUG] Only Levitation scroll is working!!

### ISSUE THREAD

**Issue by ItsOver1** [Stereowalker/C.O.M.B.A.T#64]
I have C.O.M.B.A.T. mod 1.16.1 last version and when I add something like fire bolt or explosion to my grimoire (I have fire affinity) there is a sound but nothing happen and nothing written is showing up in chat. (I'm playing on aternos server with 3 friends).
The only scroll working is levitation....I have a novice wand!
We are using applied energistic and unionlib 2.2.0 too (but I don't think it's the problem)

**Comment by Stereowalker** [comment]
Does the spell show up in the grimoire?

**Comment by ItsOver1** [comment]
Restarting the server on aternos now Is working but sometimes It still
happening. Bye I think its a server issue. Thanks anyway man and good mod
:) (Little questione: which Is the stronger affinity?)

Il ven 18 set 2020, 05:32 Stereowalker <notifications@github.com> ha
scritto:

**Comment by Stereowalker** [comment]
I don't really know which is stronger
