### ISSUE TITLE
Armor Bar Has Disappeared

### ISSUE THREAD

**Issue by seaplusbyond** [Stereowalker/C.O.M.B.A.T#66]
Basically when I activate C.O.M.B.A.T. it produces a weird bar that I'm not sure what the purpose is for. As it stands, it just blocks out (or deletes) the normal armor bar and makes it hard to determine armor levels. The only way I've seen to get the armor bar to show is by leveling up Defense, and even then it doesn't stack with normal armor. Is there a way to configure this at all or maybe it's a mod conflict? I don't really have anything else affecting armor, though. 

**_Without C.O.M.B.A.T._**
Before Armor: 
![image](https://user-images.githubusercontent.com/56456801/96039414-9a9dfc80-0e36-11eb-9802-b22cfbd56c19.png)
After Armor:
![image](https://user-images.githubusercontent.com/56456801/96039487-b7d2cb00-0e36-11eb-8b27-933cef0e7055.png)

**_With C.O.M.B.A.T._**
Before Armor:
![image](https://user-images.githubusercontent.com/56456801/96039518-c4efba00-0e36-11eb-8274-92949c384eb5.png)
After Armor:
![image](https://user-images.githubusercontent.com/56456801/96039537-cf11b880-0e36-11eb-864a-1db62ff32b12.png)

**Comment by seaplusbyond** [comment]
Update: Reproduced this with no mods installed but this and UnionLib.

**Comment by Stereowalker** [comment]
Did you get the same result after reproducing it with only those 2 mods?

**Comment by seaplusbyond** [comment]
> Did you get the same result after reproducing it with only those 2 mods?

Yeah, it had the same effect when I only had UnionLib and C.O.M.B.A.T. installed.

**Comment by Stereowalker** [comment]
Send a similar screenshot, but this time submerged in water. I want to see how it looks with the "air" meter on the screen

**Comment by seaplusbyond** [comment]
This is what I came up with:
Before Armor:
![image](https://user-images.githubusercontent.com/56456801/96213903-0c19a000-0f48-11eb-9d19-369e23f09500.png)

After Armor:
![image](https://user-images.githubusercontent.com/56456801/96213916-150a7180-0f48-11eb-8c45-d58235f706cf.png)

I'm thinking maybe it might just be a weird version of UnionLib, I'll try using some other versions from 1.16 and see what happens.
[EDIT: Tried using different versions and it didn't even load, I'm very small brain.]

**Comment by Stereowalker** [comment]
Thanks for bringing this up, it's kind of funny that I didn't notice anything was wrong up until now.

**Comment by Stereowalker** [comment]
I've fixed this in the latest update. Please check and confirm that there aren't any related errors. I'll close this issue if there's no reply within 2 days
