### ISSUE TITLE
Saving NBT data crash on world load.

### ISSUE THREAD

**Issue by ghost** [Stereowalker/C.O.M.B.A.T#71]
Mod Version: Latest
Forge: 35.1.28

Seems to be an issue on your end as I removed the mod and the game works just fine now. Might be a mod conflict, not too sure.

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 1/7/21 11:02 AM
Description: Saving entity NBT

java.lang.NullPointerException: Saving entity NBT
	at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_233772_g_(SourceFile:175) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.entity.ai.attributes.AttributeModifierManager.func_233794_c_(SourceFile:108) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_213281_b(LivingEntity.java:588) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:pmmo.mixins.json:LivingEntityChangeRespirationMixin,pl:mixin:APP:kubejs-common.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_213281_b(PlayerEntity.java:751) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,xf:fml:xaerominimap:xaero_playerentity_iswearing,xf:fml:combat:player_entity_patch,pl:mixin:APP:endergetic.mixins.json:PlayerEntityMixin,pl:mixin:APP:dungeons_gear.mixins.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_213281_b(ServerPlayerEntity.java:271) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:endergetic.mixins.json:ServerPlayerEntityMixin,pl:mixin:A}
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1412) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:EntityMixin,pl:mixin:APP:structure_gel.mixins.json:EntityMixin,pl:mixin:APP:endergetic.mixins.json:EntityMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.EntityAccess,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedPlayerList.func_72391_b(SourceFile:26) ~[?:?] {re:classloading}
	at net.minecraft.server.management.PlayerList.func_72389_g(PlayerList.java:636) ~[?:?] {re:mixin,re:classloading,xf:fml:xaeroworldmap:xaero_wm_playerlist_sendworldinfo,xf:fml:xaerominimap:xaero_playerlist_sendworldinfo,pl:mixin:APP:endergetic.mixins.json:PlayerListMixin,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:72) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_233772_g_(SourceFile:175) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.entity.ai.attributes.AttributeModifierManager.func_233794_c_(SourceFile:108) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_213281_b(LivingEntity.java:588) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:pmmo.mixins.json:LivingEntityChangeRespirationMixin,pl:mixin:APP:kubejs-common.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_213281_b(PlayerEntity.java:751) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,xf:fml:xaerominimap:xaero_playerentity_iswearing,xf:fml:combat:player_entity_patch,pl:mixin:APP:endergetic.mixins.json:PlayerEntityMixin,pl:mixin:APP:dungeons_gear.mixins.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_213281_b(ServerPlayerEntity.java:271) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:endergetic.mixins.json:ServerPlayerEntityMixin,pl:mixin:A}
-- Entity being saved --
Details:
	Entity Type: minecraft:player (net.minecraft.entity.player.ServerPlayerEntity)
	Entity ID: 313
	Entity Name: ShamanProgrammer
	Entity's Exact location: 3396.50, 85.00, -4101.50
	Entity's Block location: World: (3396,85,-4102), Chunk: (at 4,5,10 in 212,-257; contains blocks 3392,0,-4112 to 3407,255,-4097), Region: (6,-9; contains chunks 192,-288 to 223,-257, blocks 3072,0,-4608 to 3583,255,-4097)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1412) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:EntityMixin,pl:mixin:APP:structure_gel.mixins.json:EntityMixin,pl:mixin:APP:endergetic.mixins.json:EntityMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.EntityAccess,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedPlayerList.func_72391_b(SourceFile:26) ~[?:?] {re:classloading}
	at net.minecraft.server.management.PlayerList.func_72389_g(PlayerList.java:636) ~[?:?] {re:mixin,re:classloading,xf:fml:xaeroworldmap:xaero_wm_playerlist_sendworldinfo,xf:fml:xaerominimap:xaero_playerlist_sendworldinfo,pl:mixin:APP:endergetic.mixins.json:PlayerListMixin,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:72) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271] {}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6138884648 bytes (5854 MB) / 7959216128 bytes (7590 MB) up to 7959216128 bytes (7590 MB)
	CPUs: 12
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4096m -Xmx8192m
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.28-launcher.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.28-launcher.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.28-launcher.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.28-launcher.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.28-launcher.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.28
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		rhino-1.7.13.9.jar                                |Rhino                         |rhino                         |1.7.13.9            |DONE      |NOSIGNATURE
		UnionLib-1.16.4-3.1.2.jar                         |UnionLib                      |unionlib                      |3.1.2               |DONE      |NOSIGNATURE
		mystictools-1.16.3-1.3.1.jar                      |Mystic Tools                  |mystictools                   |1.16.3-1.3.1        |DONE      |NOSIGNATURE
		Otaku+World+1.16.4+V1.1.2+WP1.jar                 |Otaku World                   |otaku_world                   |1.1.2               |DONE      |NOSIGNATURE
		Bountiful+Baubles+FORGE-1.16.3-0.0.2.jar          |Bountiful Baubles             |bountifulbaubles              |NONE                |DONE      |NOSIGNATURE
		item-filters-1604.2.2.19.jar                      |Item Filters                  |itemfilters                   |1604.2.2.19         |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.1.65.jar                           |Just Enough Items             |jei                           |7.6.1.65            |DONE      |NOSIGNATURE
		AttributeFix-1.16.4-9.0.2.jar                     |AttributeFix                  |attributefix                  |9.0.2               |DONE      |ea:45:b3:82:b6:9d:50:16:95:e7:2e:34:e1:92:d5:b4:9b:69:90:d3:4f:2e:71:99:b0:be:40:80:27:1f:3e:b0
		dungeons_mobs-1.16.4-1.0.3.jar                    |Dungeons Mobs                 |dungeons_mobs                 |1.0.3               |DONE      |NOSIGNATURE
		abnormals_core-1.16.4-3.0.6.jar                   |Abnormals Core                |abnormals_core                |3.0.6               |DONE      |NOSIGNATURE
		buzzier_bees-1.16.4-3.0.0.jar                     |Buzzier Bees                  |buzzier_bees                  |3.0.0               |DONE      |NOSIGNATURE
		ContentTweaker-1.16-1.0.0.develop.9.jar           |ContentTweaker                |contenttweaker                |1.0.0.develop.9     |DONE      |NOSIGNATURE
		invtweaks-1.16.4-1.0.1.jar                        |Inventory Tweaks Renewed      |invtweaks                     |1.16.4-1.0.1        |DONE      |NOSIGNATURE
		create-mc1.16.3_v0.3b.jar                         |Create                        |create                        |mc1.16.3_v0.3b      |DONE      |NOSIGNATURE
		Waystones_1.16.3-7.3.1.jar                        |Waystones                     |waystones                     |7.3.1               |DONE      |NOSIGNATURE
		TerraForged-1.16.4-0.2.0-BETA-6.jar               |TerraForged                   |terraforged                   |0.2.0-BETA-6        |DONE      |7b:73:d0:a2:c3:40:13:84:35:4f:c9:0e:2b:85:8c:08:ea:3c:3c:eb:f1:98:8b:5b:6e:ca:8a:a0:9a:cf:12:b3
		XaerosWorldMap_1.11.6_Forge_1.16.4.jar            |Xaero's World Map             |xaeroworldmap                 |1.11.6              |DONE      |NOSIGNATURE
		shutupexperimentalsettings-1.0.1.jar              |Shutup Experimental Settings! |shutupexperimentalsettings    |1.0.1               |DONE      |NOSIGNATURE
		Placebo-1.16.3-4.3.3.jar                          |Placebo                       |placebo                       |4.3.3               |DONE      |NOSIGNATURE
		citadel-1.5.3.jar                                 |Citadel                       |citadel                       |1.5.3               |DONE      |NOSIGNATURE
		alexsmobs-1.3.0.jar                               |Alex's Mobs                   |alexsmobs                     |1.3.0               |DONE      |NOSIGNATURE
		tumbleweed-1.16-0.4.9.jar                         |Tumbleweed                    |tumbleweed                    |1.16-0.4.9          |DONE      |NOSIGNATURE
		SereneSeasons-1.16.4-4.0.0.86-universal.jar       |Serene Seasons                |sereneseasons                 |1.16.4-4.0.0.85     |DONE      |NOSIGNATURE
		gardentools-1.16.4-1.1.0.jar                      |Garden Tools                  |gardentools                   |1.16.4-1.1.0        |DONE      |1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		ftb-gui-library-1604.1.1.26.jar                   |FTB GUI Library               |ftbguilibrary                 |1604.1.1.26         |DONE      |NOSIGNATURE
		DungeonCrawl-1.16.3-2.2.3.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.2.3               |DONE      |NOSIGNATURE
		betteranimalsplus-1.16.4-10.1.0.jar               |Better Animals Plus           |betteranimalsplus             |10.1.0              |DONE      |NOSIGNATURE
		Bookshelf-1.16.4-9.3.18.jar                       |Bookshelf                     |bookshelf                     |9.3.18              |DONE      |ea:45:b3:82:b6:9d:50:16:95:e7:2e:34:e1:92:d5:b4:9b:69:90:d3:4f:2e:71:99:b0:be:40:80:27:1f:3e:b0
		sophisticatedbackpacks-1.16.4-1.2.1.124.jar       |Sophisticated Backpacks       |sophisticatedbackpacks        |1.16.4-1.2.1.124    |DONE      |NOSIGNATURE
		treemendous-1.16.3-0.4.3.jar                      |Treemendous                   |treemendous                   |0.4.3               |DONE      |NOSIGNATURE
		Apotheosis-1.16.3-4.4.1.jar                       |Apotheosis                    |apotheosis                    |4.4.1               |DONE      |NOSIGNATURE
		iceandfire-2.1.4-1.16.4.jar                       |Ice and Fire                  |iceandfire                    |2.1.4-1.16.4        |DONE      |NOSIGNATURE
		JEITweaker-1.16.4-1.0.1.5.jar                     |JEI Tweaker                   |jeitweaker                    |1.0.1.5             |DONE      |NOSIGNATURE
		traverse-1.16.4-0.4.3.8.jar                       |Traverse: Reforged            |traverse                      |1.16.4-0.4.3.8      |DONE      |NOSIGNATURE
		gunswithoutroses-1.16.4-1.0.6.jar                 |Guns Without Roses            |gunswithoutroses              |1.0.5               |DONE      |NOSIGNATURE
		CraftTweaker-1.16.2-7.0.0.27.jar                  |CraftTweaker                  |crafttweaker                  |7.0.0.27            |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.28-universal.jar                |Forge                         |forge                         |35.1.28             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		meetyourfight-1.16.4-1.1.0.jar                    |Meet Your Fight               |meetyourfight                 |1.1.0               |DONE      |NOSIGNATURE
		structure-gel-api-1.16.4-1.7.2.jar                |Structure Gel API             |structure_gel                 |1.7.2               |DONE      |NOSIGNATURE
		CraftingTweaks_1.16.3-12.2.0.jar                  |Crafting Tweaks               |craftingtweaks                |12.2.0              |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.28-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		upgrade_aquatic-1.16.4-3.0.0.jar                  |Upgrade Aquatic               |upgrade_aquatic               |3.0.0               |DONE      |NOSIGNATURE
		endergetic-1.16.4-3.0.0.jar                       |The Endergetic Expansion      |endergetic                    |3.0.0               |DONE      |NOSIGNATURE
		industrial-foregoing-1.16.4-3.2.7-7d95990.jar     |Industrial Foregoing          |industrialforegoing           |3.2.7               |DONE      |NOSIGNATURE
		theoneprobe-1.16-3.0.7.jar                        |The One Probe                 |theoneprobe                   |1.16-3.0.7          |DONE      |NOSIGNATURE
		swingthroughgrass-1.16.4-1.5.3.jar                |SwingThroughGrass             |swingthroughgrass             |1.16.4-1.5.3        |DONE      |NOSIGNATURE
		MouseTweaks-2.13-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.13                |DONE      |NOSIGNATURE
		titanium-1.16.4-3.2.4.jar                         |Titanium                      |titanium                      |3.2.4               |DONE      |NOSIGNATURE
		ftb-quests-1604.1.1.21.jar                        |FTB Quests                    |ftbquests                     |1604.1.1.21         |DONE      |NOSIGNATURE
		ImmersiveEngineering-1.16.4-4.1.2-129.jar         |Immersive Engineering         |immersiveengineering          |1.16.4-4.1.2-129    |DONE      |44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		valhelsia_structures-16.0.5.jar                   |Valhelsia Structures          |valhelsia_structures          |16.0.5              |DONE      |NOSIGNATURE
		C.O.M.B.A.T-1.16.4-7.0.0.jar                      |C.O.M.B.A.T                   |combat                        |1.16.4-7.0.0        |DONE      |NOSIGNATURE
		fairylights-4.0.4-1.16.4.jar                      |Fairy Lights                  |fairylights                   |4.0.4               |DONE      |NOSIGNATURE
		SpawnerFix-1.16.2-1.0.0.1.jar                     |Spawner Fix                   |sf                            |1.0.0.1             |DONE      |NOSIGNATURE
		atmospheric-1.16.4-3.0.0.jar                      |Atmospheric                   |atmospheric                   |3.0.0               |DONE      |NOSIGNATURE
		MCDoom-Mod-1.16.4-3.6.2-a.jar                     |Doom Mod                      |doomweapon                    |3.6.2-a             |DONE      |NOSIGNATURE
		portality-1.16.4-3.2.0.jar                        |Portality                     |portality                     |3.2.0               |DONE      |NOSIGNATURE
		curios-forge-1.16.4-4.0.3.3.jar                   |Curios API                    |curios                        |1.16.4-4.0.3.3      |DONE      |NOSIGNATURE
		Artifacts-1.16.4-2.7.3.jar                        |Artifacts                     |artifacts                     |1.16.4-2.7.3        |DONE      |NOSIGNATURE
		savageandravage-1.16.4-3.0.0.jar                  |Savage & Ravage               |savageandravage               |3.0.0               |DONE      |NOSIGNATURE
		Patchouli-1.16.4-48.jar                           |Patchouli                     |patchouli                     |1.16.4-48           |DONE      |NOSIGNATURE
		Mantle-1.16.4-1.6.52.jar                          |Mantle                        |mantle                        |1.6.52              |DONE      |NOSIGNATURE
		Xaeros_Minimap_20.30.1_Forge_1.16.4.jar           |Xaero's Minimap               |xaerominimap                  |20.30.1             |DONE      |NOSIGNATURE
		leap-1.16.4-1.0.1.jar                             |Leap                          |leap                          |1.0.1               |DONE      |NOSIGNATURE
		baubley-heart-canisters-1.16.4-1.0.0.jar          |Baubley Heart Canisters       |bhc                           |1.0                 |DONE      |NOSIGNATURE
		FastWorkbench-1.16.3-4.4.1.jar                    |FastWorkbench                 |fastbench                     |4.4.1               |DONE      |NOSIGNATURE
		autumnity-1.16.4-2.0.0.jar                        |Autumnity                     |autumnity                     |2.0.0               |DONE      |NOSIGNATURE
		StorageDrawers-1.16.3-8.2.1.jar                   |Storage Drawers               |storagedrawers                |8.2.1               |DONE      |NOSIGNATURE
		Ceramics-1.16.4-1.6.0.jar                         |Ceramics                      |ceramics                      |1.6.0               |DONE      |NOSIGNATURE
		harvest-1.16.3-1.0.3.jar                          |Harvest                       |harvest                       |1.0.3               |DONE      |NOSIGNATURE
		Survive-1.16.4-3.0.7.jar                          |Survive                       |survive                       |1.16.4-3.0.7        |DONE      |NOSIGNATURE
		tombstone-1.16-6.2.3.jar                          |Corail Tombstone              |tombstone                     |1.16-6.2.3          |DONE      |NOSIGNATURE
		guncus-1.16.4-1.3.jar                             |Gun Customization: Infinity   |guncus                        |1.16.4-1.3          |DONE      |NOSIGNATURE
		TheAbyss+2.0.0+1.16.4.jar                         |TheAbyss                      |theabyss                      |2.0.0               |DONE      |NOSIGNATURE
		NaturesAura-33.2.jar                              |Nature's Aura                 |naturesaura                   |33.2                |DONE      |NOSIGNATURE
		Project_MMO-1.16.4-3.39.9.jar                     |Project MMO                   |pmmo                          |1.16.4-3.39.9       |DONE      |NOSIGNATURE
		architectury-1.2.68-forge.jar                     |Architectury                  |architectury                  |1.2.68              |DONE      |NOSIGNATURE
		kubejs-1604.3.4.136-forge.jar                     |KubeJS                        |kubejs                        |1604.3.4.136        |DONE      |NOSIGNATURE
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |DONE      |NOSIGNATURE
		occultism-0.2.19.jar                              |Occultism                     |occultism                     |0.2.19              |DONE      |NOSIGNATURE
		mcw-furniture-2.0.0-mc1.16.4.jar                  |Macaw's Furniture             |mcwfurnitures                 |2.0.0               |DONE      |NOSIGNATURE
		CAC_Mod_2020.4-Pre1_1.16.4.jar                    |Caves And Cliffs mod          |caves_and_cliffs_mod          |MOD                 |DONE      |NOSIGNATURE
		rankine-1.16.4-1.1.4.jar                          |Project Rankine               |rankine                       |1.1.4               |DONE      |NOSIGNATURE
		FastLeafDecay-v25.jar                             |FastLeafDecay                 |fastleafdecay                 |v25                 |DONE      |NOSIGNATURE
		forge-1.16.4-geckolib-3.0.0.jar                   |GeckoLib                      |geckolib3                     |3.0.0               |DONE      |NOSIGNATURE
		OpenLoader-1.16.4-8.0.1.jar                       |OpenLoader                    |openloader                    |8.0.1               |DONE      |ea:45:b3:82:b6:9d:50:16:95:e7:2e:34:e1:92:d5:b4:9b:69:90:d3:4f:2e:71:99:b0:be:40:80:27:1f:3e:b0
		dungeons_gear-1.16.4-3.0.6.jar                    |Dungeons Gear                 |dungeons_gear                 |3.0.6               |DONE      |NOSIGNATURE
		BetterAdvancements-1.16.3-0.1.0.102.jar           |Better Advancements           |betteradvancements            |0.1.0.102           |DONE      |NOSIGNATURE
	Crash Report UUID: 0238d452-3f95-4385-82dc-96b5553e860b
	Patchouli open book context: n/a
	Player Count: 1 / 8; [ServerPlayerEntity['ShamanProgrammer'/313, l='ServerLevel[www1]', x=3396.50, y=85.00, z=-4101.50]]
	Data Packs: vanilla, mod:rhino, mod:unionlib (incompatible), mod:mystictools (incompatible), mod:otaku_world, mod:bountifulbaubles (incompatible), mod:itemfilters (incompatible), mod:jei, mod:attributefix, mod:dungeons_mobs (incompatible), mod:abnormals_core, mod:buzzier_bees, mod:contenttweaker, mod:invtweaks (incompatible), mod:create (incompatible), mod:waystones (incompatible), mod:terraforged, mod:xaeroworldmap, mod:shutupexperimentalsettings (incompatible), mod:placebo (incompatible), mod:citadel (incompatible), mod:alexsmobs, mod:tumbleweed (incompatible), mod:sereneseasons, mod:gardentools (incompatible), mod:ftbguilibrary (incompatible), mod:dungeoncrawl, mod:betteranimalsplus (incompatible), mod:bookshelf, mod:sophisticatedbackpacks, mod:treemendous, mod:apotheosis (incompatible), mod:iceandfire (incompatible), mod:jeitweaker, mod:traverse (incompatible), mod:gunswithoutroses (incompatible), mod:crafttweaker (incompatible), mod:forge, mod:meetyourfight (incompatible), mod:structure_gel, mod:craftingtweaks (incompatible), mod:upgrade_aquatic, mod:endergetic, mod:industrialforegoing (incompatible), mod:theoneprobe, mod:swingthroughgrass (incompatible), mod:mousetweaks, mod:titanium (incompatible), mod:ftbquests (incompatible), mod:immersiveengineering (incompatible), mod:valhelsia_structures (incompatible), mod:combat, mod:fairylights, mod:sf, mod:atmospheric, mod:doomweapon (incompatible), mod:portality (incompatible), mod:curios, mod:artifacts, mod:savageandravage, mod:patchouli (incompatible), mod:mantle (incompatible), mod:xaerominimap, mod:leap (incompatible), mod:bhc (incompatible), mod:fastbench (incompatible), mod:autumnity, mod:storagedrawers (incompatible), mod:ceramics (incompatible), mod:harvest (incompatible), mod:survive (incompatible), mod:tombstone, mod:guncus (incompatible), mod:theabyss, mod:naturesaura (incompatible), mod:pmmo (incompatible), mod:architectury, mod:kubejs, mod:appleskin, mod:occultism, mod:mcwfurnitures (incompatible), mod:caves_and_cliffs_mod, mod:rankine (incompatible), mod:fastleafdecay (incompatible), mod:geckolib3 (incompatible), mod:openloader, mod:dungeons_gear, mod:betteradvancements, openloader/data/contenttweaker
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by Stereowalker** [comment]
Update to 7.0.1 then confirm if this is still an issue

**Comment by Stereowalker** [comment]
I'm closing this as it should no longer be an issue. If it still is for you, then reopen it
