### ISSUE TITLE
Rings dont work in the first slot of my inventory.[BUG]

### ISSUE THREAD

**Issue by icedteal** [Stereowalker/C.O.M.B.A.T#73]
**Describe the bug**
I cant seem to find the slot in the inventory to put the ring in that is required to use spells. I've tried most of the slots and even used commands to try put it into my **inventory.slot1** and when I use the spell it just says " You do not posses an Earth affinity" am I doing something wrong or is this a bug?

**Comment by Stereowalker** [comment]
If you're using curios, use the ring slot provided by that mod. If not, press "U" to access the mods inbuilt accessory inventory and put the ring in the ring slot there

**Comment by Stereowalker** [comment]
I believe that your issue should have been resolved. If that has not been the case, feel free to reopen this issue or create a new one
