### ISSUE TITLE
[BUG] Player join on server can't move

### ISSUE THREAD

**Issue by MrJakob99** [Stereowalker/C.O.M.B.A.T#93]
**Describe the bug**
[With combat installed People that join on servers can't move, but can interact with surroundings. when in 3rd person, the player is invisible.]

**Logs**
[
[2021-05-10-6.log.gz](https://github.com/Stereowalker/C.O.M.B.A.T/files/6465952/2021-05-10-6.log.gz)
]

**To Reproduce**
[Steps to reproduce the behavior:
4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Minecraft Environment:**
 - Forge Version: 36.1.16
 - UnionLib Version: 3.3.2
 - C.O.M.B.A.T Version: 7.2.4

**Additional context**
[After removing combat everything worked again. The log shows at the and that it is stuck in some kind of loop which repeates itselfe. 
The server version of Forge is 16.1.12, don't know if that is relevant.]

**Comment by Stereowalker** [comment]
Fixed
